name: personal_finance
description: A personal finance tracking application built with Flutter and Supabase.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.3.4
  flutter_dotenv: ^5.1.0
  intl: ^0.19.0
  fl_chart: ^0.66.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - .env